mutation newStadium ($groundType: String!, $name: String!, $city: String!) {
    createStadium(stadium: {
        groundType: $groundType,
        name: $name,
        city: $city,
        })
        {
        id
    }
}